version: '3.8'

services:
  # FastAPI Backend
  api:
    build: 
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8000:9000"
    environment:
      - PYTHONPATH=/app
      - PORT=9000
      - FRONTEND_URL=http://web:8080
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  # Next.js Frontend
  web:
    build:
      context: .
      dockerfile: Dockerfile.production
    ports:
      - "3000:8080"
    environment:
      - NEXT_PUBLIC_API_URL=http://api:9000
      - API_INTERNAL_URL=http://api:9000
      - PORT=8080
    depends_on:
      api:
        condition: service_healthy
    restart: unless-stopped

networks:
  default:
    driver: bridge