apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: data-viz-satellite
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/execution-environment: gen2
        autoscaling.knative.dev/maxScale: "10"
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
      # Frontend container (Next.js) - Main container with exposed port
      - name: web
        image: gcr.io/data-viz-satellite-mvp/data-viz-satellite-frontend:latest
        ports:
        - containerPort: 8080
        env:
        - name: API_INTERNAL_URL
          value: "http://127.0.0.1:9000"
        - name: NODE_ENV
          value: "production"
        resources:
          limits:
            cpu: "2"
            memory: "2Gi"
          requests:
            cpu: "1"
            memory: "1Gi"
      
      # API container (FastAPI) - Sidecar container
      - name: api
        image: gcr.io/data-viz-satellite-mvp/data-viz-satellite-api:latest
        env:
        - name: FRONTEND_URL
          value: "http://127.0.0.1:8080"
        - name: PORT
          value: "9000"
        resources:
          limits:
            cpu: "2"
            memory: "4Gi"
          requests:
            cpu: "1"
            memory: "2Gi"
        startupProbe:
          httpGet:
            path: /health
            port: 9000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 6
        livenessProbe:
          httpGet:
            path: /health
            port: 9000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
  traffic:
  - percent: 100
    latestRevision: true