apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: data-viz-sat-mvp-single
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/execution-environment: gen2
        autoscaling.knative.dev/maxScale: "10"
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
      # Single container with both frontend and API
      - name: app
        image: gcr.io/PROJECT_ID/data-viz-satellite-combined:latest
        ports:
        - containerPort: 8080
        env:
        - name: API_INTERNAL_URL
          value: "http://127.0.0.1:8001"
        - name: MONITOR_ENABLED
          value: "false"
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "8080"
        resources:
          limits:
            cpu: "4"
            memory: "8Gi"
          requests:
            cpu: "2"
            memory: "4Gi"
        startupProbe:
          httpGet:
            path: /api/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 6
        livenessProbe:
          httpGet:
            path: /api/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
  traffic:
  - percent: 100
    latestRevision: true