#!/usr/bin/env Rscript

# Statistical Validation Utilities
# Validates statistical consistency between R and Python data generation

library(jsonlite)
library(data.table)

#' Perform comprehensive statistical validation of data generation
#' @param r_data Data generated by R backend
#' @param python_data Data generated by Python backend
#' @param alpha Significance level for statistical tests
#' @return List with statistical test results
validate_data_generation_statistics <- function(r_data, python_data, alpha = 0.05) {
  
  cat("=== Statistical Validation of Data Generation ===\n")
  
  results <- list(
    distribution_tests = list(),
    correlation_tests = list(),
    summary_statistics = list(),
    overall_valid = FALSE
  )
  
  # Convert to data.tables
  r_dt <- if (is.data.frame(r_data)) setDT(copy(r_data)) else rbindlist(r_data)
  python_dt <- if (is.data.frame(python_data)) setDT(copy(python_data)) else rbindlist(python_data)
  
  # 1. Distribution Tests
  cat("1. Testing distribution consistency...\n")
  results$distribution_tests <- test_distributions(r_dt, python_dt, alpha)
  
  # 2. Correlation Tests
  cat("2. Testing correlation structure...\n")
  results$correlation_tests <- test_correlations(r_dt, python_dt, alpha)
  
  # 3. Summary Statistics
  cat("3. Comparing summary statistics...\n")
  results$summary_statistics <- compare_summary_stats(r_dt, python_dt)
  
  # 4. Category Distribution
  cat("4. Testing category distributions...\n")
  results$category_tests <- test_category_distributions(r_dt, python_dt, alpha)
  
  # Overall validation
  results$overall_valid <- all(c(
    results$distribution_tests$all_passed,
    results$correlation_tests$all_passed,
    results$summary_statistics$all_within_tolerance,
    results$category_tests$all_passed
  ))
  
  return(results)
}

#' Test distribution consistency between R and Python data
test_distributions <- function(r_dt, python_dt, alpha = 0.05) {
  
  results <- list(
    tests = list(),
    all_passed = TRUE
  )
  
  numerical_cols <- c("log2_fold_change", "p_value", "neg_log10_p")
  
  for (col in numerical_cols) {
    if (col %in% names(r_dt) && col %in% names(python_dt)) {
      
      cat(paste("  Testing", col, "distribution...\n"))
      
      r_vals <- r_dt[[col]]
      python_vals <- python_dt[[col]]
      
      # Remove NA values
      r_vals <- r_vals[!is.na(r_vals)]
      python_vals <- python_vals[!is.na(python_vals)]
      
      # Kolmogorov-Smirnov test
      ks_test <- tryCatch({
        ks.test(r_vals, python_vals)
      }, error = function(e) {
        list(p.value = 0, statistic = 1, method = "KS test failed")
      })
      
      # Wilcoxon rank-sum test (Mann-Whitney U)
      wilcox_test <- tryCatch({
        wilcox.test(r_vals, python_vals)
      }, error = function(e) {
        list(p.value = 0, statistic = 1, method = "Wilcoxon test failed")
      })
      
      # Anderson-Darling test (if available)
      ad_test <- tryCatch({
        if (requireNamespace("kSamples", quietly = TRUE)) {
          kSamples::ad.test(r_vals, python_vals)
        } else {
          list(ad = list(p.value = NA), version = "kSamples not available")
        }
      }, error = function(e) {
        list(ad = list(p.value = NA), version = "AD test failed")
      })
      
      test_result <- list(
        column = col,
        ks_test = list(
          statistic = ks_test$statistic,
          p_value = ks_test$p.value,
          passed = ks_test$p.value > alpha
        ),
        wilcox_test = list(
          statistic = wilcox_test$statistic,
          p_value = wilcox_test$p.value,
          passed = wilcox_test$p.value > alpha
        ),
        ad_test = list(
          p_value = if (!is.null(ad_test$ad)) ad_test$ad$p.value else NA,
          passed = if (!is.null(ad_test$ad) && !is.na(ad_test$ad$p.value)) ad_test$ad$p.value > alpha else TRUE
        )
      )
      
      # Overall pass for this column
      test_result$overall_passed <- all(c(
        test_result$ks_test$passed,
        test_result$wilcox_test$passed,
        test_result$ad_test$passed
      ), na.rm = TRUE)
      
      results$tests[[col]] <- test_result
      
      if (!test_result$overall_passed) {
        results$all_passed <- FALSE
      }
    }
  }
  
  return(results)
}

#' Test correlation structure between R and Python data
test_correlations <- function(r_dt, python_dt, alpha = 0.05) {
  
  results <- list(
    correlations = list(),
    all_passed = TRUE
  )
  
  numerical_cols <- c("log2_fold_change", "p_value", "neg_log10_p")
  
  # Calculate correlation matrices
  r_cor_matrix <- tryCatch({
    cor(r_dt[, ..numerical_cols], use = "complete.obs")
  }, error = function(e) {
    matrix(NA, nrow = length(numerical_cols), ncol = length(numerical_cols))
  })
  
  python_cor_matrix <- tryCatch({
    cor(python_dt[, ..numerical_cols], use = "complete.obs")
  }, error = function(e) {
    matrix(NA, nrow = length(numerical_cols), ncol = length(numerical_cols))
  })
  
  # Compare correlation matrices
  if (!any(is.na(r_cor_matrix)) && !any(is.na(python_cor_matrix))) {
    
    cor_diff <- abs(r_cor_matrix - python_cor_matrix)
    max_cor_diff <- max(cor_diff, na.rm = TRUE)
    
    results$correlations <- list(
      r_matrix = r_cor_matrix,
      python_matrix = python_cor_matrix,
      difference_matrix = cor_diff,
      max_difference = max_cor_diff,
      within_tolerance = max_cor_diff < 0.1  # 10% tolerance for correlations
    )
    
    results$all_passed <- results$correlations$within_tolerance
    
  } else {
    results$correlations <- list(
      error = "Could not calculate correlation matrices",
      within_tolerance = FALSE
    )
    results$all_passed <- FALSE
  }
  
  return(results)
}

#' Compare summary statistics between R and Python data
compare_summary_stats <- function(r_dt, python_dt, tolerance = 0.05) {
  
  results <- list(
    comparisons = list(),
    all_within_tolerance = TRUE
  )
  
  numerical_cols <- c("log2_fold_change", "p_value", "neg_log10_p")
  
  for (col in numerical_cols) {
    if (col %in% names(r_dt) && col %in% names(python_dt)) {
      
      r_vals <- r_dt[[col]][!is.na(r_dt[[col]])]
      python_vals <- python_dt[[col]][!is.na(python_dt[[col]])]
      
      r_stats <- list(
        mean = mean(r_vals),
        median = median(r_vals),
        sd = sd(r_vals),
        min = min(r_vals),
        max = max(r_vals),
        q25 = quantile(r_vals, 0.25),
        q75 = quantile(r_vals, 0.75)
      )
      
      python_stats <- list(
        mean = mean(python_vals),
        median = median(python_vals),
        sd = sd(python_vals),
        min = min(python_vals),
        max = max(python_vals),
        q25 = quantile(python_vals, 0.25),
        q75 = quantile(python_vals, 0.75)
      )
      
      # Calculate relative differences
      relative_diffs <- list()
      within_tolerance <- TRUE
      
      for (stat_name in names(r_stats)) {
        r_val <- r_stats[[stat_name]]
        python_val <- python_stats[[stat_name]]
        
        # Calculate relative difference
        rel_diff <- if (abs(python_val) > 1e-10) {
          abs(r_val - python_val) / abs(python_val)
        } else {
          abs(r_val - python_val)
        }
        
        relative_diffs[[stat_name]] <- list(
          r_value = r_val,
          python_value = python_val,
          relative_difference = rel_diff,
          within_tolerance = rel_diff <= tolerance
        )
        
        if (rel_diff > tolerance) {
          within_tolerance <- FALSE
        }
      }
      
      results$comparisons[[col]] <- list(
        r_statistics = r_stats,
        python_statistics = python_stats,
        relative_differences = relative_diffs,
        within_tolerance = within_tolerance
      )
      
      if (!within_tolerance) {
        results$all_within_tolerance <- FALSE
      }
    }
  }
  
  return(results)
}

#' Test category distribution consistency
test_category_distributions <- function(r_dt, python_dt, alpha = 0.05) {
  
  results <- list(
    tests = list(),
    all_passed = TRUE
  )
  
  if ("category" %in% names(r_dt) && "category" %in% names(python_dt)) {
    
    # Get category counts
    r_counts <- table(r_dt$category)
    python_counts <- table(python_dt$category)
    
    # Ensure same categories
    all_categories <- union(names(r_counts), names(python_counts))
    
    r_counts_full <- sapply(all_categories, function(cat) {
      if (cat %in% names(r_counts)) r_counts[[cat]] else 0
    })
    
    python_counts_full <- sapply(all_categories, function(cat) {
      if (cat %in% names(python_counts)) python_counts[[cat]] else 0
    })
    
    # Chi-square test
    chi_test <- tryCatch({
      chisq.test(rbind(r_counts_full, python_counts_full))
    }, error = function(e) {
      list(p.value = 0, statistic = Inf, method = "Chi-square test failed")
    })
    
    results$tests$category_distribution <- list(
      r_counts = r_counts_full,
      python_counts = python_counts_full,
      chi_square_test = list(
        statistic = chi_test$statistic,
        p_value = chi_test$p.value,
        passed = chi_test$p.value > alpha
      )
    )
    
    results$all_passed <- results$tests$category_distribution$chi_square_test$passed
  }
  
  return(results)
}

# Main execution function
main <- function() {
  args <- commandArgs(trailingOnly = TRUE)
  
  if (length(args) < 2) {
    cat("Usage: Rscript statistical-validation.R <r_data.json> <python_data.json> [alpha]\n")
    quit(status = 1)
  }
  
  r_file <- args[1]
  python_file <- args[2]
  alpha <- if (length(args) >= 3) as.numeric(args[3]) else 0.05
  
  # Load data
  r_data <- fromJSON(r_file)
  python_data <- fromJSON(python_file)
  
  # Perform statistical validation
  results <- validate_data_generation_statistics(r_data, python_data, alpha)
  
  # Print summary
  cat("\n=== STATISTICAL VALIDATION SUMMARY ===\n")
  cat("Overall Valid:", results$overall_valid, "\n")
  cat("Distribution Tests Passed:", results$distribution_tests$all_passed, "\n")
  cat("Correlation Tests Passed:", results$correlation_tests$all_passed, "\n")
  cat("Summary Stats Within Tolerance:", results$summary_statistics$all_within_tolerance, "\n")
  cat("Category Tests Passed:", results$category_tests$all_passed, "\n")
  
  # Save results
  output_file <- "statistical_validation_results.json"
  write(toJSON(results, pretty = TRUE, auto_unbox = TRUE), output_file)
  cat(paste("\nDetailed results saved to:", output_file, "\n"))
  
  quit(status = if (results$overall_valid) 0 else 1)
}

# Run main if script is executed directly
if (!interactive()) {
  main()
}